<?php

/* custom routes generated by CRUD */

Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('patients', ['as'=> 'patients.index', 'uses' => 'PatientController@index']);
Route::post('patients', ['as'=> 'patients.store', 'uses' => 'PatientController@store']);
Route::get('patients/create', ['as'=> 'patients.create', 'uses' => 'PatientController@create']);
Route::put('patients/{patients}', ['as'=> 'patients.update', 'uses' => 'PatientController@update']);
Route::patch('patients/{patients}', ['as'=> 'patients.update', 'uses' => 'PatientController@update']);
Route::get('patients/{id}/delete', array('as' => 'patients.delete', 'uses' => 'PatientController@getDelete'));
Route::get('patients/{id}/confirm-delete', array('as' => 'patients.confirm-delete', 'uses' => 'PatientController@getModalDelete'));
Route::get('patients/{patients}', ['as'=> 'patients.show', 'uses' => 'PatientController@show']);
Route::get('patients/{patients}/edit', ['as'=> 'patients.edit', 'uses' => 'PatientController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('businessDetails', ['as'=> 'businessDetails.index', 'uses' => 'BusinessDetailsController@index']);
Route::post('businessDetails', ['as'=> 'businessDetails.store', 'uses' => 'BusinessDetailsController@store']);
Route::get('businessDetails/create', ['as'=> 'businessDetails.create', 'uses' => 'BusinessDetailsController@create']);
Route::put('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailsController@update']);
Route::patch('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailsController@update']);
Route::get('businessDetails/{id}/delete', array('as' => 'businessDetails.delete', 'uses' => 'BusinessDetailsController@getDelete'));
Route::get('businessDetails/{id}/confirm-delete', array('as' => 'businessDetails.confirm-delete', 'uses' => 'BusinessDetailsController@getModalDelete'));
Route::get('businessDetails/{businessDetails}', ['as'=> 'businessDetails.show', 'uses' => 'BusinessDetailsController@show']);
Route::get('businessDetails/{businessDetails}/edit', ['as'=> 'businessDetails.edit', 'uses' => 'BusinessDetailsController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('businessDetails', ['as'=> 'businessDetails.index', 'uses' => 'BusinessDetailsController@index']);
Route::post('businessDetails', ['as'=> 'businessDetails.store', 'uses' => 'BusinessDetailsController@store']);
Route::get('businessDetails/create', ['as'=> 'businessDetails.create', 'uses' => 'BusinessDetailsController@create']);
Route::put('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailsController@update']);
Route::patch('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailsController@update']);
Route::get('businessDetails/{id}/delete', array('as' => 'businessDetails.delete', 'uses' => 'BusinessDetailsController@getDelete'));
Route::get('businessDetails/{id}/confirm-delete', array('as' => 'businessDetails.confirm-delete', 'uses' => 'BusinessDetailsController@getModalDelete'));
Route::get('businessDetails/{businessDetails}', ['as'=> 'businessDetails.show', 'uses' => 'BusinessDetailsController@show']);
Route::get('businessDetails/{businessDetails}/edit', ['as'=> 'businessDetails.edit', 'uses' => 'BusinessDetailsController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('businessDetails', ['as'=> 'businessDetails.index', 'uses' => 'BusinessDetailsController@index']);
Route::post('businessDetails', ['as'=> 'businessDetails.store', 'uses' => 'BusinessDetailsController@store']);
Route::get('businessDetails/create', ['as'=> 'businessDetails.create', 'uses' => 'BusinessDetailsController@create']);
Route::put('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailsController@update']);
Route::patch('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailsController@update']);
Route::get('businessDetails/{id}/delete', array('as' => 'businessDetails.delete', 'uses' => 'BusinessDetailsController@getDelete'));
Route::get('businessDetails/{id}/confirm-delete', array('as' => 'businessDetails.confirm-delete', 'uses' => 'BusinessDetailsController@getModalDelete'));
Route::get('businessDetails/{businessDetails}', ['as'=> 'businessDetails.show', 'uses' => 'BusinessDetailsController@show']);
Route::get('businessDetails/{businessDetails}/edit', ['as'=> 'businessDetails.edit', 'uses' => 'BusinessDetailsController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('businessDetails', ['as'=> 'businessDetails.index', 'uses' => 'BusinessDetailsController@index']);
Route::post('businessDetails', ['as'=> 'businessDetails.store', 'uses' => 'BusinessDetailsController@store']);
Route::get('businessDetails/create', ['as'=> 'businessDetails.create', 'uses' => 'BusinessDetailsController@create']);
Route::put('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailsController@update']);
Route::patch('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailsController@update']);
Route::get('businessDetails/{id}/delete', array('as' => 'businessDetails.delete', 'uses' => 'BusinessDetailsController@getDelete'));
Route::get('businessDetails/{id}/confirm-delete', array('as' => 'businessDetails.confirm-delete', 'uses' => 'BusinessDetailsController@getModalDelete'));
Route::get('businessDetails/{businessDetails}', ['as'=> 'businessDetails.show', 'uses' => 'BusinessDetailsController@show']);
Route::get('businessDetails/{businessDetails}/edit', ['as'=> 'businessDetails.edit', 'uses' => 'BusinessDetailsController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('businessDetails', ['as'=> 'businessDetails.index', 'uses' => 'BusinessDetailController@index']);
Route::post('businessDetails', ['as'=> 'businessDetails.store', 'uses' => 'BusinessDetailController@store']);
Route::get('businessDetails/create', ['as'=> 'businessDetails.create', 'uses' => 'BusinessDetailController@create']);
Route::put('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::patch('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::get('businessDetails/{id}/delete', array('as' => 'businessDetails.delete', 'uses' => 'BusinessDetailController@getDelete'));
Route::get('businessDetails/{id}/confirm-delete', array('as' => 'businessDetails.confirm-delete', 'uses' => 'BusinessDetailController@getModalDelete'));
Route::get('businessDetails/{businessDetails}', ['as'=> 'businessDetails.show', 'uses' => 'BusinessDetailController@show']);
Route::get('businessDetails/{businessDetails}/edit', ['as'=> 'businessDetails.edit', 'uses' => 'BusinessDetailController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('businessDetails', ['as'=> 'businessDetails.index', 'uses' => 'BusinessDetailController@index']);
Route::post('businessDetails', ['as'=> 'businessDetails.store', 'uses' => 'BusinessDetailController@store']);
Route::get('businessDetails/create', ['as'=> 'businessDetails.create', 'uses' => 'BusinessDetailController@create']);
Route::put('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::patch('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::get('businessDetails/{id}/delete', array('as' => 'businessDetails.delete', 'uses' => 'BusinessDetailController@getDelete'));
Route::get('businessDetails/{id}/confirm-delete', array('as' => 'businessDetails.confirm-delete', 'uses' => 'BusinessDetailController@getModalDelete'));
Route::get('businessDetails/{businessDetails}', ['as'=> 'businessDetails.show', 'uses' => 'BusinessDetailController@show']);
Route::get('businessDetails/{businessDetails}/edit', ['as'=> 'businessDetails.edit', 'uses' => 'BusinessDetailController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('businessDetails', ['as'=> 'businessDetails.index', 'uses' => 'BusinessDetailController@index']);
Route::post('businessDetails', ['as'=> 'businessDetails.store', 'uses' => 'BusinessDetailController@store']);
Route::get('businessDetails/create', ['as'=> 'businessDetails.create', 'uses' => 'BusinessDetailController@create']);
Route::put('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::patch('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::get('businessDetails/{id}/delete', array('as' => 'businessDetails.delete', 'uses' => 'BusinessDetailController@getDelete'));
Route::get('businessDetails/{id}/confirm-delete', array('as' => 'businessDetails.confirm-delete', 'uses' => 'BusinessDetailController@getModalDelete'));
Route::get('businessDetails/{businessDetails}', ['as'=> 'businessDetails.show', 'uses' => 'BusinessDetailController@show']);
Route::get('businessDetails/{businessDetails}/edit', ['as'=> 'businessDetails.edit', 'uses' => 'BusinessDetailController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('businessDetails', ['as'=> 'businessDetails.index', 'uses' => 'BusinessDetailController@index']);
Route::post('businessDetails', ['as'=> 'businessDetails.store', 'uses' => 'BusinessDetailController@store']);
Route::get('businessDetails/create', ['as'=> 'businessDetails.create', 'uses' => 'BusinessDetailController@create']);
Route::put('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::patch('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::get('businessDetails/{id}/delete', array('as' => 'businessDetails.delete', 'uses' => 'BusinessDetailController@getDelete'));
Route::get('businessDetails/{id}/confirm-delete', array('as' => 'businessDetails.confirm-delete', 'uses' => 'BusinessDetailController@getModalDelete'));
Route::get('businessDetails/{businessDetails}', ['as'=> 'businessDetails.show', 'uses' => 'BusinessDetailController@show']);
Route::get('businessDetails/{businessDetails}/edit', ['as'=> 'businessDetails.edit', 'uses' => 'BusinessDetailController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('businessDetails', ['as'=> 'businessDetails.index', 'uses' => 'BusinessDetailController@index']);
Route::post('businessDetails', ['as'=> 'businessDetails.store', 'uses' => 'BusinessDetailController@store']);
Route::get('businessDetails/create', ['as'=> 'businessDetails.create', 'uses' => 'BusinessDetailController@create']);
Route::put('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::patch('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::get('businessDetails/{id}/delete', array('as' => 'businessDetails.delete', 'uses' => 'BusinessDetailController@getDelete'));
Route::get('businessDetails/{id}/confirm-delete', array('as' => 'businessDetails.confirm-delete', 'uses' => 'BusinessDetailController@getModalDelete'));
Route::get('businessDetails/{businessDetails}', ['as'=> 'businessDetails.show', 'uses' => 'BusinessDetailController@show']);
Route::get('businessDetails/{businessDetails}/edit', ['as'=> 'businessDetails.edit', 'uses' => 'BusinessDetailController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('companyDetails', ['as'=> 'companyDetails.index', 'uses' => 'CompanyDetailController@index']);
Route::post('companyDetails', ['as'=> 'companyDetails.store', 'uses' => 'CompanyDetailController@store']);
Route::get('companyDetails/create', ['as'=> 'companyDetails.create', 'uses' => 'CompanyDetailController@create']);
Route::put('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'CompanyDetailController@update']);
Route::patch('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'CompanyDetailController@update']);
Route::get('companyDetails/{id}/delete', array('as' => 'companyDetails.delete', 'uses' => 'CompanyDetailController@getDelete'));
Route::get('companyDetails/{id}/confirm-delete', array('as' => 'companyDetails.confirm-delete', 'uses' => 'CompanyDetailController@getModalDelete'));
Route::get('companyDetails/{companyDetails}', ['as'=> 'companyDetails.show', 'uses' => 'CompanyDetailController@show']);
Route::get('companyDetails/{companyDetails}/edit', ['as'=> 'companyDetails.edit', 'uses' => 'CompanyDetailController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('companyDetails', ['as'=> 'companyDetails.index', 'uses' => 'CompanyDetailController@index']);
Route::post('companyDetails', ['as'=> 'companyDetails.store', 'uses' => 'CompanyDetailController@store']);
Route::get('companyDetails/create', ['as'=> 'companyDetails.create', 'uses' => 'CompanyDetailController@create']);
Route::put('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'CompanyDetailController@update']);
Route::patch('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'CompanyDetailController@update']);
Route::get('companyDetails/{id}/delete', array('as' => 'companyDetails.delete', 'uses' => 'CompanyDetailController@getDelete'));
Route::get('companyDetails/{id}/confirm-delete', array('as' => 'companyDetails.confirm-delete', 'uses' => 'CompanyDetailController@getModalDelete'));
Route::get('companyDetails/{companyDetails}', ['as'=> 'companyDetails.show', 'uses' => 'CompanyDetailController@show']);
Route::get('companyDetails/{companyDetails}/edit', ['as'=> 'companyDetails.edit', 'uses' => 'CompanyDetailController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('businessDetails', ['as'=> 'businessDetails.index', 'uses' => 'BusinessDetailController@index']);
Route::post('businessDetails', ['as'=> 'businessDetails.store', 'uses' => 'BusinessDetailController@store']);
Route::get('businessDetails/create', ['as'=> 'businessDetails.create', 'uses' => 'BusinessDetailController@create']);
Route::put('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::patch('businessDetails/{businessDetails}', ['as'=> 'businessDetails.update', 'uses' => 'BusinessDetailController@update']);
Route::get('businessDetails/{id}/delete', array('as' => 'businessDetails.delete', 'uses' => 'BusinessDetailController@getDelete'));
Route::get('businessDetails/{id}/confirm-delete', array('as' => 'businessDetails.confirm-delete', 'uses' => 'BusinessDetailController@getModalDelete'));
Route::get('businessDetails/{businessDetails}', ['as'=> 'businessDetails.show', 'uses' => 'BusinessDetailController@show']);
Route::get('businessDetails/{businessDetails}/edit', ['as'=> 'businessDetails.edit', 'uses' => 'BusinessDetailController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('customerDetails', ['as'=> 'customerDetails.index', 'uses' => 'CustomerDetailController@index']);
Route::post('customerDetails', ['as'=> 'customerDetails.store', 'uses' => 'CustomerDetailController@store']);
Route::get('customerDetails/create', ['as'=> 'customerDetails.create', 'uses' => 'CustomerDetailController@create']);
Route::put('customerDetails/{customerDetails}', ['as'=> 'customerDetails.update', 'uses' => 'CustomerDetailController@update']);
Route::patch('customerDetails/{customerDetails}', ['as'=> 'customerDetails.update', 'uses' => 'CustomerDetailController@update']);
Route::get('customerDetails/{id}/delete', array('as' => 'customerDetails.delete', 'uses' => 'CustomerDetailController@getDelete'));
Route::get('customerDetails/{id}/confirm-delete', array('as' => 'customerDetails.confirm-delete', 'uses' => 'CustomerDetailController@getModalDelete'));
Route::get('customerDetails/{customerDetails}', ['as'=> 'customerDetails.show', 'uses' => 'CustomerDetailController@show']);
Route::get('customerDetails/{customerDetails}/edit', ['as'=> 'customerDetails.edit', 'uses' => 'CustomerDetailController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('services', ['as'=> 'services.index', 'uses' => 'ServiceController@index']);
Route::post('services', ['as'=> 'services.store', 'uses' => 'ServiceController@store']);
Route::get('services/create', ['as'=> 'services.create', 'uses' => 'ServiceController@create']);
Route::put('services/{services}', ['as'=> 'services.update', 'uses' => 'ServiceController@update']);
Route::patch('services/{services}', ['as'=> 'services.update', 'uses' => 'ServiceController@update']);
Route::get('services/{id}/delete', array('as' => 'services.delete', 'uses' => 'ServiceController@getDelete'));
Route::get('services/{id}/confirm-delete', array('as' => 'services.confirm-delete', 'uses' => 'ServiceController@getModalDelete'));
Route::get('services/{services}', ['as'=> 'services.show', 'uses' => 'ServiceController@show']);
Route::get('services/{services}/edit', ['as'=> 'services.edit', 'uses' => 'ServiceController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('appointments', ['as'=> 'appointments.index', 'uses' => 'AppointmentController@index']);
Route::post('appointments', ['as'=> 'appointments.store', 'uses' => 'AppointmentController@store']);
Route::get('appointments/create', ['as'=> 'appointments.create', 'uses' => 'AppointmentController@create']);
Route::put('appointments/{appointments}', ['as'=> 'appointments.update', 'uses' => 'AppointmentController@update']);
Route::patch('appointments/{appointments}', ['as'=> 'appointments.update', 'uses' => 'AppointmentController@update']);
Route::get('appointments/{id}/delete', array('as' => 'appointments.delete', 'uses' => 'AppointmentController@getDelete'));
Route::get('appointments/{id}/confirm-delete', array('as' => 'appointments.confirm-delete', 'uses' => 'AppointmentController@getModalDelete'));
Route::get('appointments/{appointments}', ['as'=> 'appointments.show', 'uses' => 'AppointmentController@show']);
Route::get('appointments/{appointments}/edit', ['as'=> 'appointments.edit', 'uses' => 'AppointmentController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('dentalCharts', ['as'=> 'dentalCharts.index', 'uses' => 'DentalChartController@index']);
Route::post('dentalCharts', ['as'=> 'dentalCharts.store', 'uses' => 'DentalChartController@store']);
Route::get('dentalCharts/create', ['as'=> 'dentalCharts.create', 'uses' => 'DentalChartController@create']);
Route::put('dentalCharts/{dentalCharts}', ['as'=> 'dentalCharts.update', 'uses' => 'DentalChartController@update']);
Route::patch('dentalCharts/{dentalCharts}', ['as'=> 'dentalCharts.update', 'uses' => 'DentalChartController@update']);
Route::get('dentalCharts/{id}/delete', array('as' => 'dentalCharts.delete', 'uses' => 'DentalChartController@getDelete'));
Route::get('dentalCharts/{id}/confirm-delete', array('as' => 'dentalCharts.confirm-delete', 'uses' => 'DentalChartController@getModalDelete'));
Route::get('dentalCharts/{dentalCharts}', ['as'=> 'dentalCharts.show', 'uses' => 'DentalChartController@show']);
Route::get('dentalCharts/{dentalCharts}/edit', ['as'=> 'dentalCharts.edit', 'uses' => 'DentalChartController@edit']);

});
